name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update
    - run: sudo apt install -y gcc-arm-none-eabi openscad
    - run: PICO_SDK_FETCH_FROM_GIT=1 cmake -S . -B build

    # build firmware
    - run: cmake --build build --parallel $(nproc)

    # build stls
    - run: cmake --build build --target stls --parallel $(nproc)

    - uses: actions/upload-artifact@v4.3.1
      with:
        name: snouse
        path: |
          build/snouse.uf2
          build/stls
